version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: tournaments_symfony_app
    container_name: tournaments_symfony_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - symfony

  web:
    image: nginx:latest
    container_name: tournaments_symfony_web
    restart: unless-stopped
    ports:
      - "8008:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - symfony

  db:
    image: mysql:8.0
    container_name: tournaments_symfony_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: tournaments_symfony
      MYSQL_USER: tournaments_symfony
      MYSQL_PASSWORD: tournaments_symfony
      MYSQL_ROOT_PASSWORD: toor
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3308:3306"
    networks:
      - symfony

networks:
  symfony:
    driver: bridge

volumes:
  db_data:
  database_data:
